[build]
  command = "npm run build"
  publish = "dist"  # Mantén "dist" porque usas Vite

[build.environment]
  NODE_VERSION = "20.11.1"  # Forzar versión de Node.js

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"