[build]
  command = "npm run build"
  publish = "dist"  # Cambia a "dist" porque usas Vite

[context.production]
  environment = { NODE_VERSION = "20.11.1" }  # Actualiza a una versión más reciente

[context.deploy-preview]
  command = "npm run build"